### ISSUE TITLE
Texture mods crash the game

### ISSUE THREAD

**Issue by Lilothestitch16** [Telltale-Modding-Group/DDS-D3DTX-Converter#10]
Hi. I’m doing texture mods for Kenny, Sarita, Matthew and Walter for The Walking Dead The Telltale Definitive Series but they crash my game. How can I fix this?
[Dark Outfit Matthew.zip](https://github.com/user-attachments/files/16057411/Dark.Outfit.Matthew.zip)
[Teal Sweater Walter.zip](https://github.com/user-attachments/files/16057413/Teal.Sweater.Walter.zip)
[Dark Coat and Dark Hat Kenny.zip](https://github.com/user-attachments/files/16057432/Dark.Coat.and.Dark.Hat.Kenny.zip)

**Comment by Mawrak** [comment]
Probably because you are using the tools incorrectly. Why do the files have script editor archives??? Why are you using script editor for texture mods? Also you are not giving nearly enough information for anybody to understand what you did wrong. 
Full support is offered on discord but you are banned there so you probably won't get any help with this, sorry. 
I can advise for you to learn how to do texture replacements (you do not need script editor for that, just put the new files into Archives folder) and to make sure you are using the newest version of the tool here: https://github.com/iMrShadow/DDS-D3DTX-Converter/releases/

**Comment by Lilothestitch16** [comment]
I was following a tutorial to help me learn how to do it and yeah you banned me from the Discord and because of that, I don’t wanna mod anymore. I wish I can come back and get a second chance but that probably will never happen. Also I used the DDS to D3DTX Converter to convert the modified textures back.

**Comment by Lilothestitch16** [comment]
And yes I used the newest version to do it.

**Comment by Mawrak** [comment]
I will not unban you and I will not recommend you to be unbanned to the administrator because I know you have not learned your lesson. You still haven't apologized for your awful behaviour, and we have seen what you were doing on other platforms like wikis and youtube comments, you are putting everyone through the same stuff you pulled on our server. You disrespect rules of every platform and you get very aggressive when talking about fiction. I do not see how you can possibly rejoin our server, people on the server still remember how you acted in discussions and I doubt they would welcome you back with open arms either.

**Comment by Lilothestitch16** [comment]
Well then I will not mod Telltale Games. I was going to apologize but since you guys won’t unban me, I’m not going to and because of that, I will not be modding ever again.

**Comment by iMrShadow** [comment]
Closing the issue because it was migrated to issue #11.
