### ISSUE TITLE
Batch convert feature when? 

### ISSUE THREAD

**Issue by WeaselOnaStick** [Telltale-Modding-Group/DDS-D3DTX-Converter#14]
Seems strange that this tool allows for selecting multiple files, but upon pressing "convert" only the active texture gets converted. Really looking forward to such feature, as I desperately need it for my project and I can't afford to convert hundreds of files one by one.

**Comment by iMrShadow** [comment]
Batch (bulk) conversion has been added since [v2.3.0](https://github.com/iMrShadow/DDS-D3DTX-Converter/releases/tag/2.3.0), but I got to the admit the feature is not the most intuitive thing in the world. I have stated that the [`File Explorer`](https://github.com/Telltale-Modding-Group/Telltale-Texture-Tool/wiki/Application-Guide) displays folders, which usually allows for easier navigation within your file system, but they can be also be treated as regular files. In this part of the [tutorial](https://github.com/Telltale-Modding-Group/Telltale-Texture-Tool/wiki/How-to-use-Telltale-Texture-Tool#step-34---converting-textures-to-a-regular-format) I have also stated how to do bulk conversion with the newest version.

Here is an example on how it would work:

When you click on a folder, the `From` and `To` comboboxes will list all available file type options. The `From` is the files that you are converting, the `To` is the file type they are converted to. In the screenshot below I have selected the `ui` folder containing TWDS2 textures, and I want to convert them from `D3DTX` to `DDS`.
![BATCH_CONV](https://github.com/user-attachments/assets/943c9148-5890-4386-a79d-981668740675)

To answer some questions: 
- Why can you **not** select multiple files and then convert? Isn't this more convenient?
Usually yes, but this converter works with **very sensitive** data with almost no standards. File types matter a lot too. If I allowed this feature, it would bring in tons of different bugs and scenarios, which will be hard to track and solve them.

- Why is the user allowed to select multiple files?
I specifically disabled this feature in Avalonia UI, but it appears you can still use the Ctrl key to select multiple files. Sorry about that, but I cannot do anything about it.

**Comment by WeaselOnaStick** [comment]
Thank you for a detailed answer! I made sure to see if this feature was mentioned [in the wiki](https://github.com/Telltale-Modding-Group/Telltale-Texture-Tool/wiki/Application-Guide#left-column-section) before opening an issue. Perhaps this issue warrants putting a little disclaimer in the wiki.

**Comment by iMrShadow** [comment]
Yeah, the wiki needs a note about this, since it's a frequently asked question. I want to ask you as a user, where would you expect to find this information? In Application Guide, Prelude, the tutorial or a special Q/A page?

**Comment by WeaselOnaStick** [comment]
Yeah since I was only planning on extracting the textures I didn't think to look through a multi-part modding tutorial. 
I'm not too familiar with Avalonia API, but ideally you'd allow the user to select multiple files and the converter would work as expected, since that's the most intuitive workflow. If not maybe a little unobtrusive in-app hint would show up if user selects multiple files. Wiki should be the last place for end user to look for, and to me it makes most sense to put a disclaimer [in the file browser section](https://github.com/Telltale-Modding-Group/Telltale-Texture-Tool/wiki/Application-Guide#left-column-section)

**Comment by iMrShadow** [comment]
Hello! I have added information in the [application guide](https://github.com/Telltale-Modding-Group/Telltale-Texture-Tool/wiki/Application-Guide). Does this suffice?

As for the in-app-hint, I am not planning to add it myself. I am done with the project and Avalonia for now. A PR is always welcome though!

**Comment by WeaselOnaStick** [comment]
Yeah that works, thanks for your time!

**Comment by iMrShadow** [comment]
You're welcome!

I am closing the issue.
