### ISSUE TITLE
convert button greyed out DDS DXT5

### ISSUE THREAD

**Issue by overdev93** [Telltale-Modding-Group/DDS-D3DTX-Converter#3]
Hey

I exported a lot of textures in DXT5 without any mipmaps just like the original ones from BTTF but the "convert to d3dtx" button is greyed out, the preview works tho.

no idea how to otherwise convert dds files into d3dtx

**Comment by frostbone25** [comment]
Sorry for the late reply, if the "Convert to D3DTX" is greyed out then it's likely that there are no ".header" files that accompany the DDS. 

For Version 1.0 of this app, the D3DTX Header binary data is extracted and stored into a separate file in the same directory and this is critical if you want to convert them back into a D3DTX. The button will only be greyed out if they don't exist, simply because it can't convert them back into D3DTX if it doesn't know what was originally in the D3DTX header.

For the newer app versions in the future (been busy, haven't been able to work on it lately) it has changed massively since then and I actually now know fully what is inside the file and the structure of it and can generate one from scratch (Mostly). But these .header files which just contained the "chopped" byte data from the d3dtx, are now switched to a human-readable .json text file. Although I haven't made a build yet since then due to massive changes constantly in the code/UI to accommodate for all of the new data exposed, but also more testing is needed with other D3DTX files from other games so that they are recognized and loaded correctly.
