### ISSUE TITLE
Converting to DDS hangs or crashes

### ISSUE THREAD

**Issue by thatdarkducks** [Telltale-Modding-Group/DDS-D3DTX-Converter#6]
When i try to convert my d3dtx i got from using telltale explorer, it crashes or hangs till i close it. The game i'm trying to use is Poker Night at the Inventory. I know it's not utilized for Poker Night but I just wanted to put that out there because this project looks cool :)

**Comment by thatdarkducks** [comment]
and using the beta UI tells me the file is -1 and crashes ):

**Comment by Mawrak** [comment]
This tool only supports Telltale TWD Definitive Edition at the moment. Textures from other games are not supported and may not convert properly. If you can send me the file you are trying to convert, I can take a look at whats going on but its very likely that its just unsupported format

**Comment by thatdarkducks** [comment]
sorry for my late response i forgot about this issue ):, where do i send you the file?

**Comment by Mawrak** [comment]
Hello. Since your last post we have looked into Poker Night files and I can confirm that they are NOT supported by this tool. This is the reason you get this issue. 
You can still edit textures manually with HEX editing, if you need help with that I suggest joining the modding discord server and asking in the help channel (I will send you the guide). Im in the process on writing a tutorial on manual texture editing but its not released yet

**Comment by thatdarkducks** [comment]
Alright i'll join! Where can I find the discord invite link?

**Comment by Mawrak** [comment]
here on the main page - https://github.com/Telltale-Modding-Group
I will login a bit later today

**Comment by Mawrak** [comment]
> Alright i'll join! Where can I find the discord invite link?

I added a tutorial to the wiki page - https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/wiki/%5BTutorial%5D-The-Walking-Dead-Season-1-(and-older-games)-Texture-Editing-Tutorial
